#!/bin/bash
# Access Grafana & Prometheus via Local Services

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Accessing Local Grafana & Prometheus              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✓ Services are running LOCALLY (not on remote monitor server)"
echo "✓ All metrics are being collected continuously"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "ACCESS METHODS:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "METHOD 1: Direct Local Access (if on same machine)"
echo "────────────────────────────────────────────────────────────"
echo "  Grafana:      http://localhost:3001"
echo "  Prometheus:   http://localhost:9090"
echo "  AlertManager: http://localhost:9093"
echo ""
echo "METHOD 2: SSH Port Forwarding (from Windows/Mac to these URLs)"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "For WSL/Linux terminal:"
echo "  ssh -L 3001:localhost:3001 -i ~/.ssh/id_rsa ec2-user@52.77.15.93"
echo "  Then access: http://localhost:3001 in your browser"
echo ""
echo "For Windows (PowerShell):"
echo "  ssh -L 3001:localhost:3001 -i ~/.ssh/id_rsa ec2-user@52.77.15.93"
echo "  Then access: http://localhost:3001 in your browser"
echo ""
echo "METHOD 3: Access via API Server SSH (forwarding through API server)"
echo "────────────────────────────────────────────────────────────"
echo "  ssh -J ec2-user@52.77.15.93 -L 3001:localhost:3001 ec2-user@18.142.210.110"
echo "  (Requires SSH key and API server access)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "QUICK TEST: Check if services are running locally"
echo "═══════════════════════════════════════════════════════════════"
docker ps --format "table {{.Names}}\t{{.Status}}" | grep -E "Names|prometheus|alertmanager|grafana"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ RECOMMENDATION: Using local services on this machine"
echo "═══════════════════════════════════════════════════════════════"
