#!/bin/bash
# Manual AWS Console Security Groups Update Guide
# Use this if AWS CLI credentials are not working

echo "╔════════════════════════════════════════════════════════════╗"
echo "║    Manual Security Groups Update (AWS Console)            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Since AWS CLI credentials are not working, update manually:"
echo ""
echo "STEP 1: Go to AWS Console EC2 Dashboard"
echo "────────────────────────────────────────────────────────────"
echo "1. Go to: https://us-east-1.console.aws.amazon.com/ec2/"
echo "2. Left menu: Security Groups"
echo "3. Filter by VPC: aiops-dev-vpc"
echo ""
echo "STEP 2: Update MONITOR Security Group"
echo "────────────────────────────────────────────────────────────"
echo "Security Group ID: sg-07b2facae786f1ba7"
echo "Name: aiops-dev-monitor-sg"
echo ""
echo "Actions:"
echo "1. Click on: aiops-dev-monitor-sg"
echo "2. Go to: Inbound rules tab"
echo "3. Click: Edit inbound rules"
echo "4. REMOVE rules with CIDR: 171.246.136.39/32 for ports 3000, 9090"
echo "5. ADD new rule:"
echo "   - Type: Custom TCP Rule"
echo "   - Port: 3001"
echo "   - CIDR: 0.0.0.0/0"
echo "   - Description: Grafana"
echo "   - Save"
echo "6. ADD another rule:"
echo "   - Type: Custom TCP Rule"
echo "   - Port: 9090"
echo "   - CIDR: 0.0.0.0/0"
echo "   - Description: Prometheus"
echo "   - Save"
echo ""
echo "STEP 3: Update WEB Security Group"
echo "────────────────────────────────────────────────────────────"
echo "Security Group ID: sg-07bd99bc54578289e"
echo "Name: aiops-dev-web-sg"
echo ""
echo "Actions:"
echo "1. Click on: aiops-dev-web-sg"
echo "2. Go to: Inbound rules tab"
echo "3. Click: Edit inbound rules"
echo "4. REMOVE rule with CIDR: 171.246.136.39/32 for port 8080"
echo "5. ADD new rule:"
echo "   - Type: Custom TCP Rule"
echo "   - Port: 3000"
echo "   - CIDR: 0.0.0.0/0"
echo "   - Description: Frontend"
echo "   - Save"
echo ""
echo "STEP 4: Update CORE Security Group"
echo "────────────────────────────────────────────────────────────"
echo "Security Group ID: sg-088882249fbfe9009"
echo "Name: aiops-dev-core-sg"
echo ""
echo "Actions:"
echo "1. Click on: aiops-dev-core-sg"
echo "2. Go to: Inbound rules tab"
echo "3. Click: Edit inbound rules"
echo "4. ADD new rule:"
echo "   - Type: Custom TCP Rule"
echo "   - Port: 8000"
echo "   - CIDR: 0.0.0.0/0"
echo "   - Description: API"
echo "   - Save"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  After updating, services will be accessible at:          ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║  Frontend:   http://18.139.198.122:3000                   ║"
echo "║  API:        http://52.77.15.93:8000                      ║"
echo "║  Grafana:    http://18.142.210.110:3001                   ║"
echo "║  Prometheus: http://18.142.210.110:9090                   ║"
echo "╚════════════════════════════════════════════════════════════╝"
