worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80 default_server;
        server_name _;

        location / {
            return 200 "Webserver is running\n";
            add_header Content-Type text/plain;
        }

        location /health {
            return 200 "OK\n";
            add_header Content-Type text/plain;
        }

        location /node-metrics {
            proxy_pass http://host.docker.internal:9100/metrics;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
