[monitor]
monitor-ai-01 ansible_host=52.77.67.245 private_ip=10.10.1.131 ansible_user=ec2-user

[web]
bank-web-01 ansible_host=52.220.118.140 private_ip=10.10.1.220 ansible_user=ec2-user

[core]
bank-core-01 ansible_host=54.169.238.33 private_ip=10.10.1.244 ansible_user=ec2-user

[app:children]
web
core

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/aws-hybrid
