[monitor]
monitor-ai-01 ansible_host=13.228.40.154 ansible_user=ec2-user

[web]
bank-web-01 ansible_host=13.215.240.3 ansible_user=ec2-user

[core]
bank-core-01 ansible_host=52.77.116.205 ansible_user=ec2-user

[app:children]
web
core

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/qtienle/.ssh/aws-hybrid
